function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "forloop"};
	this.sidHashMap["forloop"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "forloop:1"};
	this.sidHashMap["forloop:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "forloop:10"};
	this.sidHashMap["forloop:10"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "forloop:8"};
	this.sidHashMap["forloop:8"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "forloop:16"};
	this.sidHashMap["forloop:16"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Display"] = {sid: "forloop:17"};
	this.sidHashMap["forloop:17"] = {rtwname: "<Root>/Display"};
	this.rtwnameHashMap["<Root>/For Iterator Subsystem"] = {sid: "forloop:1"};
	this.sidHashMap["forloop:1"] = {rtwname: "<Root>/For Iterator Subsystem"};
	this.rtwnameHashMap["<Root>/For Iterator Subsystem1"] = {sid: "forloop:10"};
	this.sidHashMap["forloop:10"] = {rtwname: "<Root>/For Iterator Subsystem1"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "forloop:9"};
	this.sidHashMap["forloop:9"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "forloop:2"};
	this.sidHashMap["forloop:2"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/For Iterator"] = {sid: "forloop:3"};
	this.sidHashMap["forloop:3"] = {rtwname: "<S1>/For Iterator"};
	this.rtwnameHashMap["<S1>/Product"] = {sid: "forloop:6"};
	this.sidHashMap["forloop:6"] = {rtwname: "<S1>/Product"};
	this.rtwnameHashMap["<S1>/Unit Delay"] = {sid: "forloop:7"};
	this.sidHashMap["forloop:7"] = {rtwname: "<S1>/Unit Delay"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "forloop:4"};
	this.sidHashMap["forloop:4"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>/In1"] = {sid: "forloop:11"};
	this.sidHashMap["forloop:11"] = {rtwname: "<S2>/In1"};
	this.rtwnameHashMap["<S2>/For Iterator"] = {sid: "forloop:12"};
	this.sidHashMap["forloop:12"] = {rtwname: "<S2>/For Iterator"};
	this.rtwnameHashMap["<S2>/Product"] = {sid: "forloop:13"};
	this.sidHashMap["forloop:13"] = {rtwname: "<S2>/Product"};
	this.rtwnameHashMap["<S2>/Unit Delay"] = {sid: "forloop:14"};
	this.sidHashMap["forloop:14"] = {rtwname: "<S2>/Unit Delay"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "forloop:15"};
	this.sidHashMap["forloop:15"] = {rtwname: "<S2>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
